export const education = {
  school: "RMIT University",
  credential: "Bachelor of Computer Science",
  location: "Melbourne",
  year: "2020",
  url: "https://www.rmit.edu.au/",
  logo: "/logos/rmit.png",
};

export type Role = {
  title: string;
  company: string;
  location: string;
  range: string;
  url: string;
  logo: string;
  summary: string;
  points: string[];
  tech: string[];
};

export const experience: Role[] = [
  {
    title: "Frontend Engineer",
    company: "HBF Health",
    location: "Perth, WA (Hybrid)",
    range: "Jun 2026 – Present",
    url: "https://www.hbf.com.au/",
    logo: "/logos/hbf.png",
    summary: "HBF Health is a Perth-based private health provider.",
    points: [
      "Developed and integrated [Updoc](https://www.updoc.com.au/) Telehealth for the HBF mobile app and the [myHBF](https://my.hbf.com.au/) member portal.",
      "Integrated [Dynatrace](https://www.dynatrace.com/) tracking to monitor how members use the app and portal.",
      "Publishing [Sitecore](https://www.sitecore.com/) content updates across the HBF site.",
    ],
    tech: ["React", "Next.js", "Expo", "Sitecore", "Dynatrace", "Updoc"],
  },
  {
    title: "Senior Software Engineer",
    company: "PS Rewards",
    location: "Perth, WA (Hybrid)",
    range: "Jan 2026 – May 2026",
    url: "https://psrewards.com.au/",
    logo: "/logos/psrewards.png",
    summary:
      "PS Rewards is a rewards and cashback platform for consumers and merchants.",
    points: [
      "As the sole in-house engineer, scaled the platform from launch to 1,500 active users, owning everything from infrastructure to incident response.",
      "Designed, built and operated the entire platform end-to-end: cloud infrastructure, UX, security and on-call operations.",
      "Architected a serverless AWS stack with Hono on Lambda/API Gateway, DynamoDB single-table design via ElectroDB, Cognito JWT auth, and OpenAPI docs; deployed across four SST stages (dev, e2e, uat, production) with CloudFront, Route 53 and EventBridge.",
      "Built three Next.js 16 / React 19 / MUI v7 portals — consumer storefront, merchant dashboard, admin console — on a Turborepo monorepo backed by TanStack Query and a shared component library.",
      "Shipped a cross-platform Expo / React Native app with Face ID biometric sign-in, push notifications with gifting triggers, typed Expo Router navigation, and EAS OTA releases across uat and production channels.",
      "Delivered the gifting system end-to-end (email/push delivery, recipient redemption, dispose-on-claim security model), a dynamic campaign engine, and a unified catalog/cashback engine spanning Blackhawk Network and Rakuten.",
      "Integrated Stripe (checkout hardening, refunds, pending-order recovery, reconciliation), Blackhawk Network (mTLS gift-card supply), Rakuten affiliate offers, Twilio SMS, SendGrid, and Novatti webhooks.",
      "Patched IDOR vulnerabilities across consumer endpoints, hardened gift-card disposal against double-spend, enforced mobile verification on all orders, and shipped per-user app-version gating.",
      "Owned production deploys, DB migrations, cron monitoring, incident response, vulnerability remediation, and structured-log observability.",
      "Leveraged AI-assisted development (Claude Code, Cursor, MCP) across the entire stack, from architectural design and code review to test generation and incident debugging.",
    ],
    tech: [
      "TypeScript",
      "Hono",
      "AWS Lambda",
      "DynamoDB",
      "Cognito",
      "SST",
      "Next.js",
      "React",
      "MUI",
      "TanStack Query",
      "Turborepo",
      "Expo / React Native",
      "Stripe",
      "Playwright",
    ],
  },
  {
    title: "Senior Software Engineer",
    company: "PCCW Global",
    location: "Perth, WA (Remote)",
    range: "Jun 2024 – Dec 2025",
    url: "https://www.pccwglobal.com/",
    logo: "/logos/pccw.jpg",
    summary:
      "PCCW Global is a telecommunications and technology solutions provider.",
    points: [
      "Led development of enterprise applications using modern technologies and best practices, focusing on scalability and maintainability.",
      "Designed and implemented a scalable microservices architecture using Node.js and React.",
      "Developed and maintained business process automation workflows using Camunda.",
      "Implemented CI/CD pipelines and containerization with Docker and Kubernetes.",
      "Collaborated with cross-functional teams to deliver solutions and improve team velocity.",
      "Mentored junior developers and kept code quality consistent across the team.",
      "Participated in architecture decisions and technical planning.",
    ],
    tech: [
      "JavaScript",
      "TypeScript",
      "Camunda",
      "Node.js",
      "React.js",
      "AWS",
      "Docker",
      "Kubernetes",
      "GraphQL",
      "Jest",
      "CI/CD",
    ],
  },
  {
    title: "Software Engineer",
    company: "Valorem",
    location: "Perth, WA (Remote)",
    range: "Jan 2024 – Jun 2024",
    url: "https://www.valorem.com.au/",
    logo: "/logos/valorem.jpg",
    summary:
      "Valorem Networks provides payment platforms for workplaces, using digital automation to improve speed, flexibility, control and transparency.",
    points: [
      "Led development of a serverless payment platform using AWS and the SST framework.",
      "Integrated FrankieOne for fraud detection and Monoova for payment processing.",
      "Implemented back-end-for-frontend APIs to speed up data fetching and page loads.",
      "Built CI/CD pipelines with GitHub Actions for automated testing and deployment.",
      "Worked with the team on code quality practices that reduced production bugs.",
      "Took part in code reviews and gave technical guidance to teammates.",
    ],
    tech: [
      "SST",
      "AWS",
      "Serverless",
      "JavaScript",
      "TypeScript",
      "Node.js",
      "AWS CloudFormation",
      "DynamoDB",
      "React",
      "GraphQL",
      "Jest",
      "GitHub Actions",
    ],
  },
  {
    title: "Software Engineering Consultant",
    company: "Autom8",
    location: "Sydney, NSW (Remote)",
    range: "Aug 2023 – Jan 2024",
    url: "https://icl.autom8au.com.au/",
    logo: "/logos/autom8.png",
    summary:
      "Autom8 lets customers build custom forms, gather user data, and run rule-based processing and reporting.",
    points: [
      "Led a transformation from a monolithic architecture to client and backend services.",
      "Mapped business processes and prioritised what to implement first.",
      "Mentored the team on the new technologies.",
      "Created Jira tickets and tracked project progress.",
    ],
    tech: ["NodeJS", "Vue.js", "JavaScript", "TypeScript", "MySQL", "Docker"],
  },
  {
    title: "Software Engineer",
    company: "BPM",
    location: "Sydney, NSW",
    range: "Jan 2023 – Jul 2023",
    url: "https://landing.bigpicturemedical.com/",
    logo: "/logos/bpm.png",
    summary:
      "Big Picture Medical is a MedTech company that digitises healthcare records.",
    points: [
      "Mapped user authentication end-to-end with product designers and engineers using BPMN.",
      "Contributed to SSO login through the [National Health Service (NHS)](https://www.nhs.uk/).",
      "Built organisation-level activation for Medical Pathways so practitioners could configure pathways for their specialisations.",
      "Expanded MedKit UI, the Vue component library shared across BPM products.",
    ],
    tech: [
      "JavaScript",
      "Vue.js",
      "TypeScript",
      "GraphQL",
      "Laravel",
      "PHP",
      "PostgreSQL",
      "Linux",
      "Docker",
    ],
  },
  {
    title: "Software Engineer",
    company: "OneAffiniti",
    location: "Sydney, NSW (Remote)",
    range: "Aug 2021 – Jan 2023",
    url: "https://oneaffiniti.com/",
    logo: "/logos/oneaffiniti.png",
    summary:
      "OneAffiniti is a MarTech company focused on digital channel marketing, with clients including [Microsoft](https://www.microsoft.com/) and [Dell](https://www.dell.com/).",
    points: [
      "Built an application that generates static websites from content designed by campaign managers, cutting compute cost and making content load faster.",
      "Introduced automated code quality checks with Git hooks and linters.",
      "Brought TypeScript into JavaScript applications to keep the code consistent and catch type errors.",
      "Ran training sessions to share knowledge across teams.",
    ],
    tech: [
      "Vue.js",
      "Angular",
      "Laravel",
      "Node.js",
      "PHP",
      "AWS",
      "Terraform",
      "Linux",
      "Docker",
    ],
  },
  {
    title: "Software Developer",
    company: "Toll Group",
    location: "Sydney, NSW",
    range: "Feb 2019 – Aug 2021",
    url: "https://www.tollgroup.com/",
    logo: "/logos/toll.png",
    summary: "Toll Group is a global logistics company.",
    points: [
      "Supported a large-volume production tracking system, moving data from source devices into databases.",
      "After a [2020 ransomware attack](https://www.itnews.com.au/news/toll-groups-corporate-data-stolen-by-attackers-548033) that stole commercial agreements and employee data, helped bring servers back for business continuity and added security measures to prevent further leaks.",
    ],
    tech: [".NET", "SQL", "C#", "Azure", "Windows Server", "Laravel", "Vue.js"],
  },
];
